# Generated by Django 5.2.14 on 2026-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamgift",
            name="hubtel_checkout_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="streamgift",
            name="hubtel_reference",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="streamgift",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="streamgift",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
