# Generated by Django 6.0.1 on 2026-04-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0002_alter_order_delivery_phone_alter_order_order_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=8)),
                ("estimated_days", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Delivery"),
                            ("express", "Express Ride"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("picked_up", "Picked Up"),
                            ("en_route", "En Route"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "rider_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("pickup_location", models.CharField(blank=True, max_length=255)),
                ("dropoff_location", models.CharField(blank=True, max_length=255)),
                ("pickup_lat", models.FloatField(blank=True, null=True)),
                ("pickup_lng", models.FloatField(blank=True, null=True)),
                ("dropoff_lat", models.FloatField(blank=True, null=True)),
                ("dropoff_lng", models.FloatField(blank=True, null=True)),
                ("current_lat", models.FloatField(blank=True, null=True)),
                ("current_lng", models.FloatField(blank=True, null=True)),
                (
                    "delivery_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "proof_of_delivery",
                    models.ImageField(
                        blank=True, null=True, upload_to="deliveries/proofs/"
                    ),
                ),
                ("delivery_note", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="order.order",
                    ),
                ),
            ],
        ),
    ]
