# Generated by Django 6.0.3 on 2026-04-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='rider.riderprofile'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone'),
        ),
    ]
