# Generated by Django 6.0.1 on 2026-04-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("rider", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="rider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="rider.riderprofile",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="delivery.delivery",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="delivery.deliveryzone",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverytracking",
            constraint=models.UniqueConstraint(
                fields=("delivery",), name="unique_delivery_per_order"
            ),
        ),
    ]
