# Generated by Django 5.2.14 on 2026-05-18 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverytracking',
            name='unique_delivery_per_order',
        ),
        migrations.AddField(
            model_name='delivery',
            name='booker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_rides', to=settings.AUTH_USER_MODEL),
        ),
    ]
