# Generated by Django 6.0.1 on 2026-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentlog_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payment_pay_created_671024_idx",
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="momo_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="attempt_count",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="failed_at",
        ),
    ]
