# Generated by Django 6.0.1 on 2026-06-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_delivery_phone_alter_order_order_ref_and_more"),
        ("payment", "0003_remove_payment_payment_pay_created_671024_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("flutterwave", "Flutterwave"), ("paystack", "Paystack")],
                default="flutterwave",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider"], name="payment_pay_provide_ff0162_idx"
            ),
        ),
    ]
