# Generated by Django 6.0.1 on 2026-04-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('rider', 'Rider'), ('vendor', 'Vendor')], default='customer', max_length=10),
        ),
    ]
