# Generated by Django 6.0.1 on 2026-05-23 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Ghana phone number. Example: 0541234567 or +233541234567",
                        regex="^(?:\\+233|233|0)[0-9]{9}$",
                    )
                ],
            ),
        ),
    ]
