# Generated by Django 6.0.1 on 2026-05-23 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Ghana phone number. Example: 0558040216 or +233558040216",
                        regex="^(?:\\+233\\d{9}|233\\d{9}|0\\d{9})$",
                    )
                ],
            ),
        ),
    ]
