# Generated by Django 6.0.3 on 2026-04-06 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='riders/id_cards/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('offline', 'Offline')], default='offline', max_length=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=50.0, help_text='% of delivery fee rider gets', max_digits=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliveryzone')),
            ],
        ),
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='delivery.delivery')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='rider.riderprofile')),
            ],
        ),
    ]
