# Generated by Django 5.2.14 on 2026-08-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0003_deliveryacceptance_riderlocation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RiderNotification",
        ),
    ]
