# Generated by Django 5.2.14 on 2026-08-21 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_deliverytracking_unique_delivery_per_order_and_more"),
        ("rider", "0004_delete_ridernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderBalanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_app_cut",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_settled",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outstanding",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to="rider.riderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rider balance summaries",
            },
        ),
        migrations.CreateModel(
            name="RiderLedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rider_net", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "app_commission",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "commission_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="App % at time of delivery",
                        max_digits=5,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("momo", "Mobile Money")],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("is_settled", models.BooleanField(default=False)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("settlement_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entry",
                        to="delivery.delivery",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="rider.riderprofile",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settled_ledger_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
