# Generated by Django 5.2.14 on 2026-08-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rider", "0005_riderbalancesummary_riderledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderprofile",
            name="momo_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MTN", "MTN Mobile Money"),
                    ("VODAFONE", "Vodafone Cash"),
                    ("AIRTELTIGO", "AirtelTigo Money"),
                ],
                default="MTN",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="riderprofile",
            name="momo_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Rider MoMo number for settlement records",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="riderprofile",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("motorcycle", "Motorcycle"),
                    ("bicycle", "Bicycle"),
                    ("car", "Car"),
                    ("van", "Van"),
                    ("foot", "On Foot"),
                ],
                default="motorcycle",
                max_length=50,
            ),
        ),
    ]
