# Generated by Django 5.2.14 on 2026-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutfeature",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="aboutpage",
            options={"verbose_name": "About Page", "verbose_name_plural": "About Page"},
        ),
        migrations.AlterModelOptions(
            name="aboutstat",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="aboutfeature",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aboutstat",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="teammember",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to hide this person from the live site without deleting them.",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="story_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="team/"),
        ),
    ]
