# Generated by Django 5.2.14 on 2026-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudflag",
            name="is_confirmed_fraud",
            field=models.BooleanField(
                default=False,
                help_text="True if staff confirmed this was real fraud (payout stays held permanently). False means cleared as a false positive (payout gets released, if no other open flags remain).",
            ),
        ),
    ]
