# Generated by Django 6.0.1 on 2026-04-11 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='vendors/banners/')),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('momo_number', models.CharField(blank=True, help_text='MoMo number for payouts', max_length=15)),
                ('momo_network', models.CharField(blank=True, choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='% Lynctel takes from each sale', max_digits=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='order.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total sale before commission', max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Amount taken by Lynctel (10%)', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount vendor receives', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid Out')], default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_earnings', to='order.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='vendors.vendor')),
            ],
        ),
    ]
