# Generated by Django 6.0.1 on 2026-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_facebook_vendor_instagram_vendor_twitter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='vendor',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='momo_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Format: 233XXXXXXXXX', max_length=20),
        ),
    ]
