# Generated by Django 6.0.1 on 2026-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_remove_vendor_website_vendor_tiktok_vendor_youtube_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="tiktok",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
