# Generated by Django 6.0.1 on 2026-06-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0005_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5),
        ),
    ]
