# Generated by Django 5.2.14 on 2026-06-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0006_alter_vendor_commission_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorearning",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held (Fraud Review)"),
                    ("paid", "Paid Out"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
