# Generated by Django 5.2.14 on 2026-07-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0007_alter_vendorearning_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="paystack_subaccount_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
