# Generated by Django 5.2.14 on 2026-08-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0008_vendor_paystack_subaccount_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendorearning",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="paystack_subaccount_code",
        ),
        migrations.AddField(
            model_name="vendorearning",
            name="payout_error",
            field=models.TextField(
                blank=True,
                help_text="Error message if Hubtel payout failed — used for manual follow-up.",
            ),
        ),
        migrations.AddField(
            model_name="vendorearning",
            name="payout_reference",
            field=models.CharField(
                blank=True,
                help_text="Hubtel Transfer clientReference for this payout.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="momo_network",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("telecel", "Telecel Cash"),
                    ("vodafone", "Vodafone Cash"),
                    ("airteltigo", "AirtelTigo Money"),
                ],
                help_text="Select the network of the MoMo number above.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="momo_number",
            field=models.CharField(
                blank=True,
                help_text="MoMo number to receive order payouts (e.g. 0241234567).",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="vendorearning",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held (Fraud Review)"),
                    ("paid", "Paid Out"),
                    ("failed", "Payout Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
