# Generated by Django 6.0.1 on 2026-06-12 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0003_remove_deliverytracking_unique_delivery_per_order_and_more"),
        ("vendors", "0006_alter_vendor_commission_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="food/items/"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_spicy", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                (
                    "prep_time",
                    models.PositiveIntegerField(default=15, help_text="Minutes"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="food.foodcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FoodOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_ref",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("delivery_address", models.TextField()),
                ("delivery_lat", models.FloatField(blank=True, null=True)),
                ("delivery_lng", models.FloatField(blank=True, null=True)),
                ("delivery_phone", models.CharField(max_length=20)),
                ("delivery_note", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("distance_km", models.FloatField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash on Delivery"),
                            ("momo_on_delivery", "MoMo on Delivery"),
                            ("momo_prepaid", "MoMo (Pay Now)"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                        default="unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready for Pickup"),
                            ("picked_up", "Picked Up"),
                            ("en_route", "On the Way"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "estimated_delivery_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Estimated minutes to deliver", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_order",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FoodOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="food.fooditem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="food.foodorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cuisine",
                    models.CharField(
                        choices=[
                            ("ghanaian", "Ghanaian"),
                            ("continental", "Continental"),
                            ("chinese", "Chinese"),
                            ("fast_food", "Fast Food"),
                            ("pizza", "Pizza"),
                            ("grills", "Grills & BBQ"),
                            ("seafood", "Seafood"),
                            ("vegan", "Vegan"),
                            ("drinks", "Drinks & Juices"),
                            ("bakery", "Bakery & Pastries"),
                            ("other", "Other"),
                        ],
                        default="ghanaian",
                        max_length=20,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="food/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="food/banners/"),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Accra", max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("whatsapp", models.CharField(blank=True, max_length=15)),
                ("opening_time", models.TimeField(default="08:00")),
                ("closing_time", models.TimeField(default="22:00")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("busy", "Very Busy"),
                            ("suspended", "Suspended"),
                        ],
                        default="open",
                        max_length=15,
                    ),
                ),
                (
                    "min_order",
                    models.DecimalField(decimal_places=2, default=10, max_digits=8),
                ),
                (
                    "avg_prep_time",
                    models.PositiveIntegerField(default=20, help_text="Minutes"),
                ),
                (
                    "delivery_range",
                    models.FloatField(
                        default=10.0, help_text="Max delivery radius in km"
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_profile",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-total_orders"],
            },
        ),
        migrations.AddField(
            model_name="foodorder",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="food.foodvendor",
            ),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_items",
                to="food.foodvendor",
            ),
        ),
        migrations.AddField(
            model_name="foodcategory",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food_categories",
                to="food.foodvendor",
            ),
        ),
        migrations.CreateModel(
            name="FoodCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="food.foodvendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="food.foodcart",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.fooditem"
                    ),
                ),
            ],
            options={
                "unique_together": {("cart", "food")},
            },
        ),
    ]
