# Generated by Django 5.2.14 on 2026-08-17 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_deliverytracking_unique_delivery_per_order_and_more"),
        ("food", "0002_foodpayment_foodvendorearning"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(default="Home", max_length=60)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="foodvendor",
            name="momo_number",
            field=models.CharField(
                blank=True, help_text="MoMo number for receiving payouts", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="foodvendorearning",
            name="payout_reference",
            field=models.CharField(
                blank=True,
                help_text="Hubtel transfer reference — idempotency key",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="foodpayment",
            name="provider",
            field=models.CharField(default="hubtel", max_length=20),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="food_foodor_custome_29b2a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(
                fields=["vendor", "-created_at"], name="food_foodor_vendor__3fab52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodorder",
            index=models.Index(fields=["status"], name="food_foodor_status_822ce5_idx"),
        ),
        migrations.AddField(
            model_name="foodreview",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="foodreview",
            name="food_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="food.fooditem",
            ),
        ),
        migrations.AddField(
            model_name="foodreview",
            name="food_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="food.foodorder",
            ),
        ),
        migrations.AddField(
            model_name="savedaddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodreview",
            unique_together={("food_order", "food_item", "customer")},
        ),
        migrations.AddConstraint(
            model_name="savedaddress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("customer",),
                name="unique_default_saved_address",
            ),
        ),
    ]
