# Generated by Django 6.0.1 on 2026-04-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("products", "0004_product_discount_price_alter_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_ref",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
