# Generated by Django 5.2.14 on 2026-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_order_ref_alter_order_subtotal_and_more"),
        ("products", "0009_alter_productvideo_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="distance_km",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_lat",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_lng",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_ref",
            field=models.CharField(
                db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
