# Generated by Django 5.2.14 on 2026-06-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_add_missing_order_fields"),
        ("products", "0009_alter_productvideo_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="distance_km",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_lat",
        ),
        migrations.RemoveField(
            model_name="order",
            name="dropoff_lng",
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
    ]
