# Generated by Django 5.2.14 on 2026-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_reconcile_order_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
