# Generated by Django 5.2.14 on 2026-08-21 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_order_delivery_lat_order_delivery_lng"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("not_delivered", "Item Not Delivered"),
                            ("wrong_item", "Wrong Item Received"),
                            ("damaged", "Item Arrived Damaged"),
                            ("not_as_desc", "Not As Described"),
                            ("missing", "Missing Item(s)"),
                            ("overcharged", "Overcharged"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Describe the issue in detail"),
                ),
                (
                    "evidence",
                    models.ImageField(
                        blank=True,
                        help_text="Optional photo evidence",
                        null=True,
                        upload_to="disputes/%Y/%m/",
                    ),
                ),
                ("refund_requested", models.BooleanField(default=False)),
                ("vendor_response", models.TextField(blank=True)),
                ("vendor_responded_at", models.DateTimeField(blank=True, null=True)),
                ("staff_notes", models.TextField(blank=True)),
                ("resolution", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Under Review"),
                            ("resolved", "Resolved — Refund Approved"),
                            ("closed", "Closed — No Action"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
