# Generated by Django 5.2.14 on 2026-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_orderdispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="distance_km",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="hubtel_checkout_id",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="hubtel_reference",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="order",
            name="order_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
