# Generated by Django 6.0.1 on 2026-06-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="MP4 recommended. Max 50MB. Keep under 60 seconds.",
                        upload_to="product_videos/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional thumbnail image shown before video plays.",
                        null=True,
                        upload_to="product_video_thumbs/",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
