# Generated by Django 6.0.1 on 2026-06-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productvideo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_slug_3edc0c_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_status_041708_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_created_52f0d7_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_is_feat_a5d7cd_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_video_thumbs/"
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(upload_to="product_videos/"),
        ),
    ]
