# Generated by Django 5.2.14 on 2026-06-28 01:45

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_products_pr_slug_3edc0c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                upload_to="product_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "webm"]
                    ),
                    products.models.validate_video_file_size,
                ],
            ),
        ),
    ]
