# Generated by Django 5.2.14 on 2026-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_productvideo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flash_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sale price during flash sale — must be lower than selling_price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_ends",
            field=models.DateTimeField(
                blank=True,
                help_text="Flash sale expires at this UTC datetime",
                null=True,
            ),
        ),
    ]
