# Generated by Django 5.2.14 on 2026-08-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_flash_sale_fields"),
        ("vendors", "0009_alter_vendorearning_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "sort_order"], name="category_active_sort_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "-created_at"], name="product_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "is_featured"], name="product_status_featured_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="product_category_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["selling_price"], name="product_selling_price_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["flash_sale_ends"], name="product_flash_sale_ends_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "status"], name="product_vendor_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["-views"], name="product_views_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="productimage_primary_idx"
            ),
        ),
    ]
